name: cds
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py27_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_3
  - pip=19.3.1=py27_0
  - python=2.7.17=h9bab390_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.4.0=py27_0
  - sqlite=3.30.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py27_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.8.1
    - astor==0.8.0
    - backports-weakref==1.0.post1
    - catkin-pkg==0.4.14
    - docutils==0.15.2
    - easydict==1.9
    - enum34==1.1.6
    - funcsigs==1.0.2
    - functools32==3.2.3.post2
    - futures==3.3.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.24.1
    - h5py==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - mock==3.0.5
    - numpy==1.16.5
    - opencv-python==3.4.3.18
    - opt-einsum==2.3.2
    - protobuf==3.10.0
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - pyyaml==5.1.2
    - rospkg==1.1.10
    - simple-pid==0.2.4
    - six==1.12.0
    - tensorboard==2.0.0
    - tensorflow-estimator==2.0.1
    - tensorflow-gpu==2.0.0
    - termcolor==1.1.0
    - tqdm==4.39.0
    - werkzeug==0.16.0
    - wrapt==1.11.2

